/**
 * Abbreviations that appear in the exam questions, answers and explanations,
 * with what they stand for. The answer feedback lists the ones a question
 * uses. Add an entry when new questions bring a new abbreviation.
 */
export const abbreviations: Record<string, string> = {
  A2A: 'Agent2Agent, an open protocol that lets agents call each other',
  ACI: 'Azure Container Instances',
  ACL: 'Access control list',
  ACR: 'Azure Container Registry',
  AD: 'Active Directory (now Microsoft Entra ID for the cloud version)',
  'AD DS': 'Active Directory Domain Services, the on-premises directory service',
  ADE: 'Azure Disk Encryption, which uses BitLocker or DM-Crypt inside the VM',
  ADLS: 'Azure Data Lake Storage',
  AES: 'Advanced Encryption Standard, a symmetric encryption algorithm',
  AI: 'Artificial intelligence',
  AKS: 'Azure Kubernetes Service',
  ALM: 'Application lifecycle management, moving work from development to test to production',
  AMA: 'Azure Monitor Agent, which collects logs and metrics from machines',
  ANN: 'Approximate nearest neighbor, a fast vector search that trades a little accuracy for speed',
  API: 'Application programming interface',
  ARM: 'Azure Resource Manager, the deployment and management layer of Azure',
  ASG: 'Application security group, a way to group VMs in network security rules',
  AUC: 'Area under the (ROC) curve, a measure of classification quality',
  AWS: 'Amazon Web Services',
  BCDR: 'Business continuity and disaster recovery',
  BGP: 'Border Gateway Protocol, used to exchange routes between networks',
  BI: 'Business intelligence (as in Power BI)',
  BLEU: 'Bilingual Evaluation Understudy, a text similarity score for generated text',
  BM25: 'Best Matching 25, the classic keyword ranking function used in full-text search',
  C2PA: 'Coalition for Content Provenance and Authenticity, content credentials for generated media',
  CD: 'Continuous delivery or continuous deployment',
  CDC: 'Change data capture, which records inserts, updates and deletes from the transaction log',
  CDN: 'Content delivery network',
  CEF: 'Common Event Format, a log format used by security appliances',
  CI: 'Continuous integration',
  CIDR: 'Classless Inter-Domain Routing, the notation for IP address ranges such as 10.0.0.0/16',
  CLI: 'Command-line interface (as in Azure CLI)',
  CORS: 'Cross-origin resource sharing, which lets a web page call another domain',
  CPK: 'Customer-provided key, an encryption key sent with each storage request',
  CPU: 'Central processing unit',
  CQRS: 'Command Query Responsibility Segregation, separating reads from writes',
  CSPM: 'Cloud security posture management',
  CSV: 'Comma-separated values',
  CTE: 'Common table expression, a named temporary result in a T-SQL query',
  DAB: 'Data API builder, which exposes database objects as REST and GraphQL endpoints',
  DB: 'Database',
  DCR: 'Data collection rule, which says what Azure Monitor Agent collects and where it goes',
  DDM: 'Dynamic Data Masking',
  DDoS: 'Distributed denial of service, an attack that floods a service with traffic',
  DLQ: 'Dead-letter queue, where messages that cannot be processed are moved',
  DMV: 'Dynamic management view, a view of SQL Server state and performance',
  DNAT: 'Destination network address translation',
  DNS: 'Domain Name System, which turns names into IP addresses',
  DPO: 'Direct preference optimization, fine-tuning from preferred and rejected answers',
  DR: 'Disaster recovery',
  DSPM: 'Data security posture management',
  EA: 'Enterprise Agreement, a Microsoft licensing agreement for large organizations',
  EASM: 'External attack surface management',
  FIFO: 'First in, first out: messages are handled in the order they arrive',
  FIPS: 'Federal Information Processing Standards, US government security standards',
  FQDN: 'Fully qualified domain name',
  FTP: 'File Transfer Protocol',
  GB: 'Gigabyte',
  GCP: 'Google Cloud Platform',
  GPU: 'Graphics processing unit',
  GPv1: 'General-purpose v1, the older storage account type',
  GPv2: 'General-purpose v2, the standard storage account type',
  GRS: 'Geo-redundant storage: three copies in one region plus three in the paired region',
  GZRS: 'Geo-zone-redundant storage: copies across three zones plus three in the paired region',
  HA: 'High availability',
  HNSW: 'Hierarchical Navigable Small World, an index for fast approximate vector search',
  HPA: 'Horizontal Pod Autoscaler, which adds or removes Kubernetes pods',
  HSM: 'Hardware security module, tamper-resistant hardware that protects keys',
  HTML: 'HyperText Markup Language',
  HTTP: 'Hypertext Transfer Protocol',
  HTTPS: 'HTTP over TLS, the encrypted version of HTTP',
  IaaS: 'Infrastructure as a service: you manage the OS and apps on cloud VMs',
  IaC: 'Infrastructure as code, such as Bicep, ARM templates or Terraform',
  IDaaS: 'Identity as a service',
  IDE: 'Integrated development environment',
  IIS: 'Internet Information Services, the Windows web server',
  ILB: 'Internal load balancer',
  IOPS: 'Input/output operations per second, a disk performance measure',
  IPv4: 'Internet Protocol version 4, addresses like 10.0.0.4',
  IPv6: 'Internet Protocol version 6, the newer, longer address format',
  ICMP: 'Internet Control Message Protocol, used by ping',
  IoT: 'Internet of Things',
  IP: 'Internet Protocol (an IP address identifies a device on a network)',
  JIT: 'Just-in-time, as in VM access that opens ports only when requested',
  JSON: 'JavaScript Object Notation, a text format for structured data',
  JSONL: 'JSON Lines, one JSON object per line (used for training data)',
  JWK: 'JSON Web Key, a public key published in JSON form',
  KB: 'Kilobyte',
  KEDA: 'Kubernetes Event-driven Autoscaling',
  KNN: 'k-nearest neighbors, finding the k most similar vectors',
  KQL: 'Kusto Query Language, used in Log Analytics and Azure Data Explorer',
  LDAP: 'Lightweight Directory Access Protocol',
  LFS: 'Large File Storage (Git LFS), for large binary files in Git',
  LLM: 'Large language model',
  LRS: 'Locally redundant storage: three copies in one datacenter',
  MAE: 'Mean absolute error',
  MAXDOP: 'Maximum degree of parallelism, how many processors one query can use',
  MB: 'Megabyte',
  MCA: 'Microsoft Customer Agreement',
  MCP: 'Model Context Protocol, a standard way for AI agents to call tools',
  MFA: 'Multifactor authentication',
  ML: 'Machine learning',
  MPI: 'Message Passing Interface, used for distributed training',
  MRL: 'Matryoshka Representation Learning, embeddings that can be shortened',
  MTO: 'Maximum tolerable outage',
  NAT: 'Network address translation',
  NFS: 'Network File System, a file sharing protocol used mostly on Linux',
  NIC: 'Network interface card',
  NoSQL: 'Non-relational database (not only SQL)',
  NSG: 'Network security group, which allows or denies traffic to Azure resources',
  NTFS: 'NT File System, the Windows file system',
  NVA: 'Network virtual appliance, such as a third-party firewall VM',
  OCI: 'Open Container Initiative, the standard format for container images',
  OCR: 'Optical character recognition, reading text from images',
  OData: 'Open Data Protocol, a convention for query options in REST APIs',
  OIDC: 'OpenID Connect, a sign-in protocol built on OAuth 2.0',
  OLTP: 'Online transaction processing',
  OS: 'Operating system',
  OSI: 'Open Systems Interconnection, the 7-layer network model',
  P1: 'Microsoft Entra ID P1, the first premium license tier',
  P2: 'Microsoft Entra ID P2, the premium tier that adds Identity Protection and PIM',
  PaaS: 'Platform as a service: Azure runs the OS and runtime, you deploy the app',
  'PCI DSS': 'Payment Card Industry Data Security Standard',
  PDF: 'Portable Document Format',
  PII: 'Personally identifiable information',
  PIM: 'Privileged Identity Management, for just-in-time admin roles',
  PSI: 'Population stability index, a measure of data drift',
  PTU: 'Provisioned throughput unit, reserved model capacity in Azure OpenAI',
  'RA-GRS': 'Read-access geo-redundant storage: GRS plus read access to the secondary region',
  'RA-GZRS': 'Read-access geo-zone-redundant storage: GZRS plus read access to the secondary region',
  RAG: 'Retrieval-augmented generation: search your data and give the results to the model',
  RBAC: 'Role-based access control',
  RCSI: 'Read committed snapshot isolation',
  REST: 'Representational state transfer, the style of most HTTP APIs',
  RFT: 'Reinforcement fine-tuning',
  RLS: 'Row-level security',
  RMSE: 'Root mean squared error',
  ROI: 'Return on investment',
  ROUGE: 'Recall-Oriented Understudy for Gisting Evaluation, a summary quality score',
  RPO: 'Recovery point objective: how much data loss, in time, is acceptable',
  RRF: 'Reciprocal Rank Fusion, merging keyword and vector search rankings',
  RSA: 'Rivest-Shamir-Adleman, an asymmetric encryption algorithm',
  RTO: 'Recovery time objective: how long a service may be down',
  RU: 'Request unit, the Azure Cosmos DB measure of throughput cost',
  SaaS: 'Software as a service: a finished app you just use',
  SAS: 'Shared access signature, a token that grants limited access to storage',
  SDK: 'Software development kit',
  SFTP: 'SSH File Transfer Protocol',
  SFT: 'Supervised fine-tuning, training a model on example prompts and answers',
  SKU: 'Stock keeping unit, the tier or size of an Azure resource',
  SLA: 'Service level agreement, the uptime Microsoft guarantees',
  SLI: 'Service level indicator, a measured value such as latency',
  SLO: 'Service level objective, the target for an indicator',
  SMB: 'Server Message Block, the Windows file sharing protocol',
  SNAT: 'Source network address translation, used for outbound connections',
  SNMP: 'Simple Network Management Protocol',
  SOC: 'Security operations center',
  SQL: 'Structured Query Language',
  SSE: 'Server-Sent Events, a one-way HTTP streaming format',
  SSH: 'Secure Shell, encrypted remote login to Linux machines',
  SSL: 'Secure Sockets Layer, the predecessor of TLS',
  SSML: 'Speech Synthesis Markup Language',
  SSO: 'Single sign-on',
  SSPR: 'Self-service password reset',
  TCP: 'Transmission Control Protocol',
  TDE: 'Transparent data encryption',
  TLS: 'Transport Layer Security, which encrypts network traffic',
  TPM: 'Tokens per minute, a model throughput quota',
  TTL: 'Time to live, how long an item is kept before it expires',
  UDF: 'User-defined function',
  UDP: 'User Datagram Protocol',
  UDR: 'User-defined route, a custom route table entry',
  UI: 'User interface',
  URI: 'Uniform resource identifier',
  URL: 'Uniform resource locator, a web address',
  UTC: 'Coordinated Universal Time',
  VIP: 'Virtual IP address',
  VM: 'Virtual machine',
  VNet: 'Virtual network',
  VPN: 'Virtual private network',
  vTPM: 'Virtual Trusted Platform Module',
  WAF: 'Web application firewall, which blocks common web attacks',
  XDR: 'Extended detection and response, as in Microsoft Defender XDR',
  XML: 'Extensible Markup Language',
  YAML: 'YAML Ain’t Markup Language, the format of pipeline and config files',
  ZRS: 'Zone-redundant storage: three copies across three availability zones in one region'
};

// Longest first, so 'RA-GRS' wins over 'GRS' and 'AD DS' over 'AD'.
const terms = Object.keys(abbreviations).sort((a, b) => b.length - a.length);
const escape = (term: string) => term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const pattern = new RegExp(`(?<![\\w-])(${terms.map(escape).join('|')})s?(?![\\w-])`, 'g');

/**
 * The abbreviations used in the given texts, in order of first use.
 * Plurals such as 'VMs' count as 'VM'; non-breaking hyphens count as hyphens.
 */
export function findAbbreviations(texts: string[]): { term: string; meaning: string }[] {
  const found: string[] = [];
  for (const text of texts) {
    text.replace(/‑/g, '-').replace(pattern, (match, term: string) => {
      if (!found.includes(term)) found.push(term);
      return match;
    });
  }
  return found.map((term) => ({ term, meaning: abbreviations[term] }));
}
