services:
  azure-practice-exams:
    image: carvenmartisit/azure-practice-exams:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    restart: unless-stopped
